# To run locally
# npx @techdocs/cli serve -v -c ./doc/mkdocs.yml
# 
site_name: 'k6-studio Internal Documentation'
repo_url: https://github.com/grafana/k6-studio
edit_uri: edit/main/doc/docs

theme:
  name: material
  features:
    - navigation.sections

plugins:
  - techdocs-core
